### ISSUE TITLE
Forge just crashes

### ISSUE THREAD

**Issue by ghost** [W-OVERFLOW/NoHurtCam#4]
Forge just crashes when i use this mod. Im using multi mc forge latest version

**Comment by Scherso** [comment]
@6lockk Can you provide a log file or a crash report of you using the mod?

**Comment by ghost** [comment]
> @6lockk Can you provide a log file or a crash report of you using the mod?

im sorry im just stupid i used the wrong version lol please delete this thread im sorry for the inconvenience
