### ISSUE TITLE
why does it install essentials mod

### ISSUE THREAD

**Issue by verbes4** [W-OVERFLOW/NoHurtCam#6]
why

**Comment by Scherso** [comment]
It's cause it uses the config library, I'm probably gonna get rid of Essential soon since it sucks

**Comment by Scherso** [comment]
For now, you can use NotSoEssential which removes it's annoying features

**Comment by verbes4** [comment]
> For now, you can use NotSoEssential which removes it's annoying features

oh thats awesome thanks
